apiVersion: v1
kind: Service
metadata:
  name: reddit-service
  labels:
    app: reddit
spec:
  type: LoadBalancer # Changed to LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: reddit